### ISSUE TITLE
error should be set when server response with an error

### ISSUE THREAD

**Issue by niicojs** [alex-cory/use-http#134]
**Describe the bug**
When the server respond with an error (like 500 for example), data should be null and error should be the error.

**Expected behavior**
When calling fetch, `response` should be check with `response.ok`, if response is not ok, error should be set, not data.

**Comment by alex-cory** [comment]
What is the error to be? What if it's just an error code?

**Comment by alex-cory** [comment]
`response.status === 404`
are we to say
`error === 'Not Found'`?

**Comment by niicojs** [comment]
English is not my native language so having to compare strings feels weird to me. I would say error === 404 but I don't know how other libs does that.
Maybe `message === Not Found` but allow access to the full response somehow?

**Comment by alex-cory** [comment]
Okay, I'll make it so if `!response.ok` then set an error.

**Comment by denizdogan** [comment]
Currently, is there any way to handle a 404 apart from implementing "manual" handling?

```js
const { loading, error, data } = useFetch(`${BASE_URL}/${uuid}`, [uuid]);
// the above is a 404 but error is undefined
```

Thanks

**Comment by alex-cory** [comment]
I will try to fix this today.

**Comment by alex-cory** [comment]
It's implemented and works, but I need to make tests first. You can see the [PR here](https://github.com/alex-cory/use-http/pull/166/files)

**Comment by Zdenek-M** [comment]
> Currently, is there any way to handle a 404 apart from implementing "manual" handling?
> 
> ```js
> const { loading, error, data } = useFetch(`${BASE_URL}/${uuid}`, [uuid]);
> // the above is a 404 but error is undefined
> ```

I used version 0.2.5 and when server returns 404, I get the error:

error: TypeError: Failed to execute 'text' on 'Response': body stream is locked at _callee

**Comment by Zdenek-M** [comment]
> I used version 0.2.5 and when server returns 404, I get the error:
> 
> error: TypeError: Failed to execute 'text' on 'Response': body stream is locked at _callee

This error was due to fact that my server returned text error message, not json. When the response with status 404 contains json in its body, error is undefined.

**Comment by alex-cory** [comment]
Yes, you can do
```js
const { loading, error, data, response } = useFetch(`${BASE_URL}/${uuid}`, [uuid])
// check if !response.ok
```

**Comment by denizdogan** [comment]
@alex-cory Don't stress out over it, take your time :) We all have work and personal lives to take care of! Thanks

**Comment by alex-cory** [comment]
Okay everyone, this should be fixed in `v0.2.6`. I'm going to close this, but do comment back on here if something is not working and I'll reopen the issue!

**Comment by theowenyoung** [comment]
Hi, @alex-cory , I still don't know how to get error when promise resolved, 

```javascript
  const { get, response, error } = useFetch("/xxxx") 
  useEffect(() => {
    const init = async () => {
      await get()
      if(!response.ok){
        // how to get error here?
        console.log('error ',error );
      }
    }
      init()
  }, [])
```
