### ISSUE TITLE
useFetch with react-router

### ISSUE THREAD

**Issue by danzawadzki** [alex-cory/use-http#187]
Hi,
I don't know if it's a bug or my mistake, but I have a problem using the library with a react-router.

What I'm trying to do is to make a request to API when:
1. component is mounting to get the first page of the players list, which contains 25 items.
2. when someone changes page number or number of players.

Everything works fine when you first mount a component. When I change the route to other and return to the player list again, the hook does not start up. Just like it would not be mounted again.

My code:
```
	enum PageSize {
		SMALL = 15,
		MEDIUM = 25,
		LARGE = 40
	}

	const [page, setPage] = useState<number>(1);
	const [size, setSize] = useState<PageSize>(PageSize.SMALL);

	const { loading, error, data } = useFetch(
		{
			path: PlayersApi.ALL({
				page,
				size
			}),
			data: []
		},
		[size, page]
	);
```

I reproduced the problem in the following link. When you first enter the Dashboard route, everything works fine. At the second, unfortunately, not anymore. 

[Sandbox](https://codesandbox.io/s/zealous-mirzakhani-958j3?fontsize=14&hidenavigation=1&theme=dark)

I don't know how to deal with it. I suspect it would be easiest to pass on a different key to the track every time route changes and listen to it in deps array, but is there another way out?

**Comment by alex-cory** [comment]
From a quick glance this seems like a bug. I will take a look at this asap

**Comment by alex-cory** [comment]
As a temporary workaround you can do
```js
const { loading, data } = useFetch(url, {
    cachePolicy: 'no-cache'
  }, [id]);
```
You can also set this in your `Provider` so you don't have to do this everywhere.
```js
import { Provider } from 'use-http'

const App = () => (
  <Provider options={{ cachePolicy: 'no-cache' }}>
    {/* rest of app */}
  </Provider>
)
```
Also, side note. You can just do this
```js
const { loading, data } = useFetch(url, [id])
```
Not required to do
```js
const { loading, data } = useFetch(url, {}, [id]) // <- extra empty options object
```

**Comment by danzawadzki** [comment]
Hi Alex! Thanks! Disabling cache completely solved my problem. Thanks also for your tip! Looks much cleaner! :)

**Comment by danzawadzki** [comment]
Hi Alex! Thanks! Disabling cache completely solved my problem. Thanks also for your tip! Looks much cleaner! :)

**Comment by alex-cory** [comment]
I'm going to re-open this issue just so I can keep tabs on it and take a deeper look at this later

**Comment by alex-cory** [comment]
I think this should be fixed with `v0.3.3`. If not, respond to this thread with "it's not working" and I'll re-open the issue and take another look.

**Comment by tanvir002700** [comment]
I thing this bug is still exists. When I goto small page size last page to larger page, its not update the data state. onNewData it's got newData, but state not change with new data.
